"""PostgreSQL persistence for student questions used by professor reports."""

import psycopg
from app.core.config import settings


def _connect() -> psycopg.Connection:
    return psycopg.connect(
        host=settings.DB_HOST,
        port=settings.DB_PORT,
        dbname=settings.DB_NAME,
        user=settings.DB_USER,
        password=settings.DB_PASSWORD,
        connect_timeout=10,
    )


def initialize_question_store() -> None:
    """Create the database/table if this is the first app startup."""
    with _connect() as connection:
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS student_questions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                course_name TEXT NOT NULL,
                message TEXT NOT NULL,
                session_id TEXT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        connection.execute(
            """CREATE INDEX IF NOT EXISTS idx_student_questions_course_created
               ON student_questions(course_name, created_at)"""
        )


def save_student_question(
    *, message: str, course_name: str | None, session_id: str | None
) -> None:
    """Store a question before generating the AI response."""
    with _connect() as connection:
        connection.execute(
            """
            INSERT INTO student_questions(course_name, message, session_id)
            VALUES (%s, %s, %s)
            """,
            (
                (course_name or "미지정").strip() or "미지정",
                message.strip(),
                session_id,
            ),
        )


def get_student_questions(course_name: str) -> list[str]:
    """Return stored questions for a course in chronological order."""
    with _connect() as connection:
        rows = connection.execute(
            """
            SELECT message
            FROM student_questions
            WHERE course_name = %s
            ORDER BY created_at ASC, id ASC
            """,
            (course_name.strip(),),
        ).fetchall()
    return [row[0] for row in rows]
